# Generated by Django 2.0 on 2018-10-18 11:54

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181008_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.build_category_image_path),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
