# Generated by Django 2.0 on 2018-10-08 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181007_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 9, 8, 12, 15, 971674, tzinfo=utc)),
        ),
    ]
