# Generated by Django 2.0 on 2018-10-08 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181008_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 9, 8, 30, 34, 316304, tzinfo=utc)),
        ),
    ]
