# Generated by Django 2.0 on 2018-10-09 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181009_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 17, 36, 56, 468269, tzinfo=utc)),
        ),
    ]
