# Generated by Django 2.0 on 2018-10-18 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181009_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 19, 11, 54, 19, 314588, tzinfo=utc)),
        ),
    ]
